# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32a0164e387713251e2797a1a04902282a1e56f9c67a8591a3a9029419f9a2ae302af6dc24385718f6f922a8590c6080065f90a2c533f658af6bee349b6859fa

test:
  secret_key_base: 2f1f36439dc5a92154bc02721c6761cbe96286265359b3a4359328c9769fbcc7f468c6187aa033171cb64ddfd6d9e5d7df934c665c02f6f7b4703f1c1ee7760c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
